### ISSUE TITLE
Compiling the example?

### ISSUE THREAD

**Issue by richardlalancette** [mellinoe/veldrid-spirv#16]
I'm trying to figure out how to use this.

Where is `factory` coming from?

**Comment by mellinoe** [comment]
@richardlalancette This library is an extension to [Veldrid](https://veldrid.dev), and the "factory" there is a ResourceFactory. The best place to find a working example of Veldrid.SPIRV is in the [NeoDemo example project](https://github.com/mellinoe/veldrid/tree/master/src/NeoDemo) in the main Veldrid repository. Most of the shaders used there are compiled with this library.

**Comment by richardlalancette** [comment]
Fantastic! thank you!

I got one of your shader to cross compile last night! Thank you!
