### ISSUE TITLE
Update SPIRV-Cross

### ISSUE THREAD

**Issue by tgjones** [mellinoe/veldrid-spirv#3]
I found a bug in SPIRV-Cross, which has now been fixed:
https://github.com/KhronosGroup/SPIRV-Cross/issues/796#issuecomment-454996302

Please could you cut a new release based on the latest version of SPIRV-Cross? I’m not sure what update schedule you have in mind, no problem if this doesn’t fit with that.

(By the way, the fix for the bug I reported only applies when the platform is set to macOS, but as far as I can tell Veldrid.SPIRV doesn’t specify the MSL target so it defaults to macOS, which happens to work out for me.)

**Comment by mellinoe** [comment]
@tgjones Sorry about the delay -- I will try to get to this over the weekend.

**Comment by mellinoe** [comment]
I've updated the repository and fixed a number of native build issues, but I'm still waiting on the CI builds to complete before uploading the NuGet package.

**Comment by tgjones** [comment]
Thank you, it's much appreciated!

**Comment by mellinoe** [comment]
@tgjones Unfortunately, the (better) way that I'm building SPIRV-Cross and other native deps has broken the iOS static library, and I am still working through how to build it correctly. Unless I'm going to include 10 static libs in the NuGet package (no thanks), I need to configure the build to produce a combined static library, which I'm not yet familiar with. Hopefully it's not that difficult.

**Comment by mellinoe** [comment]
Sorry for the delay; 1.0.7 is now up on NuGet and should include the fix you linked in the first message.
