### ISSUE TITLE
Update shaderc

### ISSUE THREAD

**Issue by SomeAnon42** [mellinoe/veldrid-spirv#6]
It seems like the version currently used by Veldrid.SPIRV is not quite up-to-date. For instance, it doesn't allow me to use GL_EXT_samplerless_texture_functions, which is definitely supported in newer builds. Do you think you could make a new release based on the latest version?

**Comment by mellinoe** [comment]
This is on my list of things to do. The upgrade process should be smoother than last time since I cleaned up how shaderc was being pulled in and referenced.

**Comment by mellinoe** [comment]
1.0.8 is up on NuGet.org which includes the latest versions of shaderc and SPIRV-Cross.
